packages:
  - 'sdk'
  - 'text'
  - 'desktop'
  - 'goose-binary/*'
overrides:
  react: ^19.2.4
  react-dom: ^19.2.4
nodeLinker: hoisted
allowBuilds:
  '@modelcontextprotocol/ext-apps': true
  electron: true
  electron-winstaller: true
  esbuild: true
